composer.json, src/DataResponse.php, src/DataResponseFactory.php, src/DataResponseFactoryInterface.php, src/DataResponseFormatterInterface.php, src/Formatter/HtmlDataResponseFormatter.php, src/Formatter/JsonDataResponseFormatter.php, src/Formatter/XmlDataResponseFormatter.php, src/Middleware/FormatDataResponse.php, src/Middleware/FormatDataResponseAsHtml.php, src/Middleware/FormatDataResponseAsJson.php, src/Middleware/FormatDataResponseAsXml.php, tests/DataResponseTest.php, tests/Formatter/HtmlDataResponseFormatterTest.php, tests/Formatter/JsonDataResponseFormatterTest.php, tests/Formatter/XmlDataResponseFormatterTest.php, tests/Middleware/FormatDataResponseTest.php
=> Move from yii-web

.phpstorm.meta.php/DataResponseFactoryInterface.php
| Is bugfix?    |
| New feature?  |
| Breaks BC?    |
| Fixed issues  |
=> Move .phpstorm.meta.php from yii-web

src/DataResponse.php
=> fix namespace

.scrutinizer.yml
=> Update php version in scrutinizer config

src/DataResponseFactory.php
| Fixed issues  | fix protected modifier
=> fix protected modifier

tests/Formatter/JsonDataResponseFormatterTest.php
| Fixed issues  | Json formatter tests
=> Json formatter tests

tests/Formatter/XmlDataResponseFormatterTest.php
| Fixed issues  | Xml formatter tests
=> Xml formatter tests

src/Formatter/HtmlDataResponseFormatter.php, tests/Formatter/HtmlDataResponseFormatterTest.php
| Fixed issues  | Html formatter tests
=> Html formatter tests

tests/Middleware/FormatDataResponseTest.php
| Fixed issues  | Middleware tests
=> Middleware tests

tests/DataResponseFactoryTest.php
| Fixed issues  | Add data response factory tests
=> Add data response factory tests

tests/DataResponseTest.php
| Fixed issues  | Add data response tests
=> Add data response tests

composer.json, config/web.php
=> Add base configuration

src/DataResponse.php, src/Formatter/JsonDataResponseFormatter.php, tests/DataResponseTest.php, tests/Formatter/JsonDataResponseFormatterTest.php
| Breaks BC?    | ✔️
| Fixed issues  | https://github.com/yiisoft/yii-web/issues/320
=> Fix json data response formatter

src/Formatter/XmlDataResponseFormatter.php, tests/Formatter/XmlDataResponseFormatterTest.php
| Is bugfix?    | ✔️/❌
| Breaks BC?    | ✔️
=> Add use XmlSerializer to XmlDataResponseFormatter

README.md, config/web.php, src/Middleware/ContentNegotiator.php, tests/Middleware/ContentNegotiatorTest.php
=> Add ContentNegotiator middleware

composer.json, phpunit.xml.dist, src/DataResponse.php, src/Middleware/ContentNegotiator.php, tests/Middleware/ContentNegotiatorTest.php
Static tests fail incorrect. Created issue: https://github.com/vimeo/psalm/issues/5646
=> Add tests and minor improve ContentNegotiator

src/DataResponse.php, tests/DataResponseTest.php, tests/Stub/FakeDataResponseFormatter.php
=> Fix formating with called withResponseFormatter

src/DataResponse.php
| Fixed issues  | Fix psalm errors
=> Fix psalm errors

composer.json, src/DataResponseFormatterInterface.php, src/Formatter/JsonDataResponseFormatter.php, src/Formatter/XmlDataResponseFormatter.php, tests/Formatter/XmlDataResponseFormatterTest.php
| Fixed issues  | #36, https://github.com/yiisoft/serializer/issues/19
=> Remove serializer usage,  rename variable to DataResponseFormatterInterface

src/Formatter/XmlDataInterface.php, src/Formatter/XmlDataResponseFormatter.php, tests/Formatter/XmlDataResponseFormatterTest.php
=> Refactoring object formatting in XmlDataResponseFormatter

src/Formatter/XmlDataInterface.php, src/Formatter/XmlDataResponseFormatter.php, tests/Formatter/XmlDataResponseFormatterTest.php
=> Add attributes to XML tag when XML formatting

src/Formatter/XmlDataResponseFormatter.php, tests/Formatter/XmlDataResponseFormatterTest.php
=> Add support for objects to XML formatting

composer.json, tests/Formatter/XmlDataResponseFormatterTest.php
=> Add `ext-dom` to composer.json and more test

README.md, composer.json, phpunit.xml.dist, psalm.xml, src/DataResponse.php, src/DataResponseFactory.php, src/DataResponseFactoryInterface.php, src/DataResponseFormatterInterface.php, src/Formatter/HtmlDataResponseFormatter.php, src/Formatter/JsonDataResponseFormatter.php, src/Formatter/XmlDataResponseFormatter.php, src/Middleware/ContentNegotiator.php, src/Middleware/FormatDataResponse.php, src/Middleware/FormatDataResponseAsHtml.php, src/Middleware/FormatDataResponseAsJson.php, src/Middleware/FormatDataResponseAsXml.php, src/ResponseContentTrait.php, tests/DataResponseFactoryTest.php, tests/DataResponseTest.php, tests/Formatter/HtmlDataResponseFormatterTest.php, tests/Formatter/JsonDataResponseFormatterTest.php, tests/Formatter/XmlDataResponseFormatterTest.php, tests/Middleware/ContentNegotiatorTest.php, tests/Middleware/FormatDataResponseTest.php, tests/TestCase.php
=> Cleanup, add docBlocks, improve tests

src/DataResponse.php, tests/DataResponseTest.php, tests/Stub/CustomDataResponseFormatter.php
=> Fix using a formatter with a custom body

tests/DataResponseTest.php
=> Raise percentage of mutation score indicator

composer.json, config/params.php, config/web.php
Merge after https://github.com/yiisoft/di/pull/241
=> Move formatters to params

README.md, src/DataResponse.php, src/ResponseContentTrait.php, tests/DataResponseFactoryTest.php, tests/DataResponseTest.php, tests/Formatter/HtmlDataResponseFormatterTest.php, tests/Formatter/JsonDataResponseFormatterTest.php, tests/Formatter/XmlDataResponseFormatterTest.php, tests/Middleware/ContentNegotiatorTest.php, tests/Middleware/FormatDataResponseTest.php, tests/Stub/RecursiveDataResponseFormatter.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
=> Separate chain calls
